export const CONFIGURE_CURRENT_GAME = 'configure_current_game'
export const END_OF_LEVEL = 'end_of_level'
export const SET_RESULT = 'set_result'
export const INCREMENT_LEVEL = 'increment_level'
export const GAME_OVER = 'game_over'
export const GAME_OVER_BUT_NOT_LOOSE = 'game_over_but_not_loose'
export const SEND_HIGHSCORE = 'send_highscore'

export const FETCH_USER = 'fetch_user'

export const INVALID_PASSWORD_OR_EMAIL = 'invalid_passwor_or_email'
export const INVALID_REGISTRATION_DATA = 'invalid_registration_data'

export const GET_BEST_PLAYERS = 'get_best_players'
export const GET_HIGHSCORES = 'get_highscores'
export const GET_USER_BY_ID = 'get_user_by_id'

export const OPEN_SOCKET = 'open_socket'
export const GET_DUEL_ROOMS = 'get_tables'
export const SET_DUEL_ROOM = 'set_duel_room'
export const NEW_CHAT_MESSAGE = 'new_chat_message'
export const FRESH_PLAYER_LIST = 'fresh_player_list'
export const CLEAR_DUEL_ROOM = 'clear_duel_room'
export const CLEAR_CHAT = 'clear_chat'
export const CLEAR_PLAYERS = 'clear_players'
export const START_DUEL_GAME = 'start_duel_game'
export const SHOW_INPUT_FIELD = 'show_input_field'
export const SET_ANSWER_CORRECTNESS = 'set_answer_correctness'
export const SHOW_SCOREBOARD = 'show_scoreboard'